Repository jdomingu98/ft_irc, pull requests merged in 2024-04, with the labels that each got.

#51 feat: kick command
  Makefile
  includes/Channel.hpp
  includes/commands/KickCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/KickParser.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/InviteCommand.cpp
  src/commands/KickCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/JoinParser.cpp
  src/parser/KickParser.cpp
Labels: enhancement

#52 10 Comando Mode
  Makefile
  includes/Channel.hpp
  includes/commands/ModeCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/parser/CommandParser.hpp
  includes/parser/ModeParser.hpp
  src/Channel.cpp
  src/commands/InviteCommand.cpp
  src/commands/ModeCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/ModeParser.cpp
Labels: enhancement

#53 join validation complete
  includes/libsUtils.hpp
  src/commands/JoinCommand.cpp
Labels: enhancement

#57 46 varios bugs en join part
  includes/Channel.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/commands/JoinCommand.hpp
  includes/commands/ModeCommand.hpp
  includes/libsUtils.hpp
  includes/parser/ModeParser.hpp
  src/Channel.cpp
  src/Server.cpp
  src/User.cpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/ModeCommand.cpp
  src/commands/NickCommand.cpp
  src/commands/PartCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/JoinParser.cpp
  src/parser/KickParser.cpp
  src/parser/ModeParser.cpp
Labels: bug

#54 35 privmsg mensajes privados a canales
  includes/Server.hpp
  includes/User.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  src/Server.cpp
  src/User.cpp
  src/commands/PrivateMessageCommand.cpp
  src/parser/PrivateMessageParser.cpp
Labels: enhancement

#60 [BUG] El usuario no necesita registrarse para ejecutar comandos
  Makefile
  includes/Server.hpp
  includes/commands/ACommand.hpp
  includes/commands/ICommand.hpp
  includes/commands/InviteCommand.hpp
  includes/commands/JoinCommand.hpp
  includes/commands/KickCommand.hpp
  includes/commands/ModeCommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PartCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/UserCommand.hpp
  includes/parser/CommandParser.hpp
  includes/parser/IParser.hpp
  includes/parser/InviteParser.hpp
  includes/parser/JoinParser.hpp
  includes/parser/KickParser.hpp
  includes/parser/ModeParser.hpp
  includes/parser/NickParser.hpp
  includes/parser/PartParser.hpp
  includes/parser/PassParser.hpp
  includes/parser/PrivateMessageParser.hpp
  includes/parser/QuitParser.hpp
  includes/parser/UserParser.hpp
  src/Server.cpp
  src/commands/ACommand.cpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/commands/ModeCommand.cpp
  src/commands/NickCommand.cpp
  src/commands/PartCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/PrivateMessageCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/InviteParser.cpp
  src/parser/JoinParser.cpp
  src/parser/KickParser.cpp
  src/parser/ModeParser.cpp
  src/parser/NickParser.cpp
  src/parser/PartParser.cpp
  src/parser/PassParser.cpp
  src/parser/PrivateMessageParser.cpp
  src/parser/QuitParser.cpp
  src/parser/UserParser.cpp
Labels: bug

#41 Comando topic
  Makefile
  includes/Channel.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/commands/TopicCommand.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/TopicParser.hpp
  src/Channel.cpp
  src/Server.cpp
  src/User.cpp
  src/commands/TopicCommand.cpp
  src/libsUtils.cpp
  src/main.cpp
  src/parser/CommandParser.cpp
  src/parser/TopicParser.cpp
Labels: enhancement

#61 5 gestion de signals
  includes/Server.hpp
  includes/libsUtils.hpp
  src/Server.cpp
  src/main.cpp
Labels: enhancement

#67 62 comandos por partes
  includes/Server.hpp
  includes/libsUtils.hpp
  src/Server.cpp
Labels: enhancement

#68 65 bug ningun error al mandar un comando inexistente
  includes/exceptions/CommandNotFoundException.hpp
  includes/exceptions/exceptions.hpp
  src/Server.cpp
  src/main.cpp
  src/parser/CommandParser.cpp
Labels: bug

#72 64 bugs comando kick
  includes/Channel.hpp
  includes/User.hpp
  includes/commands/InviteCommand.hpp
  includes/commands/JoinCommand.hpp
  includes/commands/KickCommand.hpp
  includes/commands/ModeCommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PartCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/TopicCommand.hpp
  includes/commands/UserCommand.hpp
  includes/libsUtils.hpp
  src/Channel.cpp
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/libsUtils.cpp
  src/main.cpp
  src/parser/KickParser.cpp
  src/parser/PartParser.cpp
  src/parser/TopicParser.cpp
Labels: bug

#63 Funcionalidades del mode
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/ModeCommand.cpp
  src/libsUtils.cpp
  src/parser/JoinParser.cpp
  src/parser/ModeParser.cpp
Labels: enhancement

#73 71 bug user command no funciona correctamente
  src/commands/UserCommand.cpp
  src/parser/UserParser.cpp
Labels: bug

#75 59 bug lista de tokens con huecos vacios
  src/Server.cpp
  src/parser/CommandParser.cpp
Labels: bug

#78 feat: make it compile on MacOS
  src/Server.cpp
Labels: bug

#76 70 bug comportamiento incorrecto quit
  includes/Server.hpp
  includes/commands/KickCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/libsUtils.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/commands/QuitCommand.cpp
  src/parser/QuitParser.cpp
Labels: bug, enhancement

#83 79 splitear input por rn
  src/Server.cpp
Labels: bug

#84 feat: prefix parse
  includes/parser/CommandParser.hpp
  src/Server.cpp
  src/parser/CommandParser.cpp
Labels: bug

#85 Resolve some topic bugs
  includes/Channel.hpp
  includes/commands/TopicCommand.hpp
  includes/libsUtils.hpp
  includes/parser/TopicParser.hpp
  src/Channel.cpp
  src/commands/TopicCommand.cpp
  src/parser/TopicParser.cpp
Labels: bug

#97 change comment of Quit
  src/Server.cpp
Labels: bug

#99 fix(join command): Messages sent when joining to channel
  includes/commands/JoinCommand.hpp
  includes/libsUtils.hpp
  src/commands/JoinCommand.cpp
Labels: bug

#100 fix: channels are created without passwords
  src/commands/JoinCommand.cpp
Labels: bug

#101 feat(joinParser): change arguments validation
  src/parser/JoinParser.cpp
Labels: bug

#104 fix(send): dont throw exception when client close connection
  src/Server.cpp
Labels: bug

#103 fix(join command): Create more than one channel at a time
  src/commands/JoinCommand.cpp
Labels: bug

#98 86 bug cambiar comportamiento funcion join
  includes/exceptions/IgnoreCommandException.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  src/Server.cpp
  src/commands/NickCommand.cpp
  src/libsUtils.cpp
  src/parser/CommandParser.cpp
  src/parser/KickParser.cpp
  src/parser/QuitParser.cpp
  src/parser/TopicParser.cpp
  src/parser/UserParser.cpp
Labels: bug

#106 change de RPL macros
  includes/commands/JoinCommand.hpp
  includes/libsUtils.hpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/TopicCommand.cpp
Labels: bug

#105 fix(quit): one message per involved users
  includes/User.hpp
  includes/libsUtils.hpp
  src/User.cpp
  src/commands/QuitCommand.cpp
Labels: bug

#109 bug QUIT without register
  src/commands/QuitCommand.cpp
Labels: bug

#110 feat(kick): more options to kick
  includes/commands/KickCommand.hpp
  src/commands/KickCommand.cpp
  src/parser/KickParser.cpp
Labels: bug

#130 fix(join command): Send rpl topic on user joining when is set
  src/commands/JoinCommand.cpp
Labels: bug

#132 fix(mode): refactor makeOperAnUser function
  src/Channel.cpp
Labels: bug

#134 bug privMsg to channel
  src/User.cpp
Labels: bug

#131 fix(invite): send invited user invite_msg
  includes/libsUtils.hpp
  src/commands/InviteCommand.cpp
Labels: bug

#133 Bug invite msg
  src/commands/InviteCommand.cpp
Labels: bug

#136 feat: handle disconnection on PasswordMismatch exception
  src/Server.cpp
Labels: bug

#137 feat: remove exception
  includes/exceptions/exceptions.hpp
  src/commands/NickCommand.cpp
Labels: bug

#135 fix register msg
  includes/libsUtils.hpp
  src/User.cpp
  src/libsUtils.cpp
Labels: bug

#129 117 part bug no se sale de canales si no existe uno en medio
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/commands/PartCommand.cpp
  src/commands/PrivateMessageCommand.cpp
Labels: bug

#139 fix bug Mode msg #122
  includes/libsUtils.hpp
  src/commands/ModeCommand.cpp
Labels: bug

#140 ENH singleton utils
  Makefile
  includes/Server.hpp
  includes/Utils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/IParser.hpp
  includes/parser/InviteParser.hpp
  includes/parser/JoinParser.hpp
  includes/parser/KickParser.hpp
  includes/parser/NickParser.hpp
  includes/parser/PartParser.hpp
  includes/parser/PassParser.hpp
  includes/parser/PrivateMessageParser.hpp
  includes/parser/QuitParser.hpp
  includes/parser/TopicParser.hpp
  includes/parser/UserParser.hpp
  src/User.cpp
  src/Utils.cpp
  src/commands/ModeCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/JoinParser.cpp
  src/parser/KickParser.cpp
  src/parser/PartParser.cpp
  src/parser/PrivateMessageParser.cpp
Labels: enhancement

#138 115 utils bug cambiar user id macros rpl por error msg
  Makefile
  includes/Channel.hpp
  includes/Logger.hpp
  includes/Responses.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/Utils.hpp
  includes/commands/ACommand.hpp
  includes/commands/InviteCommand.hpp
  includes/commands/JoinCommand.hpp
  includes/commands/KickCommand.hpp
  includes/commands/ModeCommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PartCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/TopicCommand.hpp
  includes/commands/UserCommand.hpp
  includes/exceptions/IRCException.hpp
  includes/exceptions/IgnoreCommandException.hpp
  includes/exceptions/ServerException.hpp
  includes/exceptions/exceptions.hpp
  includes/parser/CommandParser.hpp
  includes/parser/IParser.hpp
  includes/parser/InviteParser.hpp
  includes/parser/JoinParser.hpp
  includes/parser/KickParser.hpp
  includes/parser/ModeParser.hpp
  includes/parser/NickParser.hpp
  includes/parser/PartParser.hpp
  includes/parser/PassParser.hpp
  includes/parser/PrivateMessageParser.hpp
  includes/parser/QuitParser.hpp
  includes/parser/TopicParser.hpp
  includes/parser/UserParser.hpp
  src/Channel.cpp
  src/Logger.cpp
  src/Responses.cpp
  src/Server.cpp
  src/User.cpp
  src/Utils.cpp
  src/commands/ACommand.cpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/commands/ModeCommand.cpp
  src/commands/PartCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/PrivateMessageCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/TopicCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/PrivateMessageParser.cpp
Labels: bug

#142 74 mode bug review parseo
  includes/Channel.hpp
  includes/commands/ModeCommand.hpp
  includes/exceptions/exceptions.hpp
  src/Channel.cpp
  src/commands/ModeCommand.cpp
  src/parser/ModeParser.cpp
Labels: bug

#143 141 server bug no usar errno en el proyecto
  includes/Channel.hpp
  includes/Server.hpp
  includes/Utils.hpp
  src/Server.cpp
  src/User.cpp
  src/Utils.cpp
Labels: bug

#144 125 nick bug respuestas
  includes/Responses.hpp
  src/commands/NickCommand.cpp
Labels: bug

#146 fix(privmsg): deleted CannotSendToChannel
  includes/exceptions/exceptions.hpp
  src/commands/PrivateMessageCommand.cpp
Labels: bug

#155 fix(server): borrar el inputbuffer del cliente
  src/Server.cpp
Labels: bug

#156 148 nick bug no se envia bien nick msg
  src/commands/NickCommand.cpp
Labels: bug

#159 fix(parse): empty is empty, not " " and stuff
  src/parser/CommandParser.cpp
Labels: bug

#160 feat: vector with pointers for avoiding copies
  includes/Channel.hpp
  src/Channel.cpp
  src/Responses.cpp
  src/User.cpp
  src/commands/JoinCommand.cpp
  src/commands/KickCommand.cpp
  src/commands/NickCommand.cpp
  src/commands/PartCommand.cpp
  src/commands/QuitCommand.cpp
Labels: bug
