Repository jdomingu98/ft_irc, pull requests merged in 2024-03, with the labels that each got.

#19 4 autenticacion
  Makefile
  includes/Server.hpp
  includes/User.hpp
  includes/commands/ICommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/UserCommand.hpp
  includes/exceptions/CommandException.hpp
  includes/exceptions/ParserException.hpp
  includes/exceptions/ServerException.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/IParser.hpp
  includes/parser/NickParser.hpp
  includes/parser/PassParser.hpp
  includes/parser/QuitParser.hpp
  includes/parser/UserParser.hpp
  includes/utils.hpp
  src/Server.cpp
  src/User.cpp
  src/commands/NickCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/UserCommand.cpp
  src/main.cpp
  src/manteca.cpp
  src/parser/CommandParser.cpp
  src/parser/NickParser.cpp
  src/parser/PassParser.cpp
  src/parser/QuitParser.cpp
  src/parser/UserParser.cpp
  src/utils.cpp
Labels: documentation, enhancement

#23 Respuestas al cliente
  includes/Server.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/UserCommand.hpp
  includes/exceptions/CommandException.hpp
  includes/exceptions/CommandNotFoundException.hpp
  includes/exceptions/IRCException.hpp
  includes/exceptions/ParserException.hpp
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/NickParser.hpp
  includes/parser/PassParser.hpp
  includes/parser/QuitParser.hpp
  includes/parser/UserParser.hpp
  src/Server.cpp
  src/commands/NickCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/NickParser.cpp
  src/parser/PassParser.cpp
  src/parser/QuitParser.cpp
  src/parser/UserParser.cpp
Labels: enhancement

#25 16 crear clase channel
  Makefile
  includes/Channel.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/exceptions/ChannelException.hpp
  includes/libsUtils.hpp
  src/Channel.cpp
  src/Server.cpp
  src/User.cpp
Labels: enhancement

#29 ci: add workflow to see if it compiles
  .github/workflows/doesItCompile.yml
Labels: CI

#27 fix: update validation
  includes/Server.hpp
  includes/User.hpp
  includes/commands/ICommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/UserCommand.hpp
  includes/exceptions/IRCException.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/QuitParser.hpp
  src/Server.cpp
  src/User.cpp
  src/commands/NickCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/NickParser.cpp
  src/parser/PassParser.cpp
  src/parser/QuitParser.cpp
  src/parser/UserParser.cpp
Labels: bug, documentation

#33 Comando privmsg
  Makefile
  includes/Server.hpp
  includes/User.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/parser/CommandParser.hpp
  includes/parser/PrivateMessageParser.hpp
  src/Server.cpp
  src/User.cpp
  src/commands/PrivateMessageCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/PrivateMessageParser.cpp
Labels: enhancement

#38 15 hacer un readme bonito
  LICENSE.md
  README.md
Labels: documentation

#40 feat: Applied singleton pattern to Server class
  Makefile
  includes/Channel.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/commands/ICommand.hpp
  includes/commands/JoinCommand.hpp
  includes/commands/NickCommand.hpp
  includes/commands/PassCommand.hpp
  includes/commands/PrivateMessageCommand.hpp
  includes/commands/QuitCommand.hpp
  includes/commands/UserCommand.hpp
  includes/exceptions/ChannelException.hpp
  includes/libsUtils.hpp
  includes/utils.hpp
  src/Server.cpp
  src/User.cpp
  src/commands/JoinCommand.cpp
  src/commands/NickCommand.cpp
  src/commands/PassCommand.cpp
  src/commands/PrivateMessageCommand.cpp
  src/commands/QuitCommand.cpp
  src/commands/UserCommand.cpp
  src/libsUtils.cpp
  src/main.cpp
  src/parser/PrivateMessageParser.cpp
Labels: enhancement

#44 Comando invite
  Makefile
  includes/Channel.hpp
  includes/Server.hpp
  includes/User.hpp
  includes/commands/InviteCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  includes/parser/CommandParser.hpp
  includes/parser/InviteParser.hpp
  src/Channel.cpp
  src/Server.cpp
  src/User.cpp
  src/commands/InviteCommand.cpp
  src/commands/JoinCommand.cpp
  src/commands/UserCommand.cpp
  src/parser/CommandParser.cpp
  src/parser/InviteParser.cpp
Labels: enhancement

#48 feat: join messages
  includes/commands/JoinCommand.hpp
  includes/exceptions/exceptions.hpp
  includes/libsUtils.hpp
  src/commands/JoinCommand.cpp
Labels: enhancement

#50 added validation of channels to join
  src/parser/JoinParser.cpp
Labels: bug
